package Enums;

public enum Actions{                          
	
	NOT_STARTING_TRANSPORTATION, STARTING_TRANSPORTATION, COMPLETION_TRANSPORTATION, 
	ABORTING_TRANSPORTATION, MOVING_ELEVATOR, BOARDING, DEBOARDING;
	
}